//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.27 at 09:56:25 PM IST 
//


package com.arun.ws.invoice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arun.ws.invoice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceCountRequest_QNAME = new QName("http://arun.com/ws/invoice-ops/", "invoiceCountRequest");
    private final static QName _InvoiceCountResponse_QNAME = new QName("http://arun.com/ws/invoice-ops/", "invoiceCountResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arun.ws.invoice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceCountRequest }
     * 
     */
    public InvoiceCountRequest createInvoiceCountRequest() {
        return new InvoiceCountRequest();
    }

    /**
     * Create an instance of {@link InvoiceCountResponse }
     * 
     */
    public InvoiceCountResponse createInvoiceCountResponse() {
        return new InvoiceCountResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceCountRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arun.com/ws/invoice-ops/", name = "invoiceCountRequest")
    public JAXBElement<InvoiceCountRequest> createInvoiceCountRequest(InvoiceCountRequest value) {
        return new JAXBElement<InvoiceCountRequest>(_InvoiceCountRequest_QNAME, InvoiceCountRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceCountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://arun.com/ws/invoice-ops/", name = "invoiceCountResponse")
    public JAXBElement<InvoiceCountResponse> createInvoiceCountResponse(InvoiceCountResponse value) {
        return new JAXBElement<InvoiceCountResponse>(_InvoiceCountResponse_QNAME, InvoiceCountResponse.class, null, value);
    }

}
