//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.27 at 09:56:25 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://arun.com/ws/invoice-ops/")
package com.arun.ws.invoice.model;
